name: Hourly Webhook Trigger

on:
  schedule:
    - cron: "0 * * * *"   # every hour at minute 0
  workflow_dispatch:       # enables manual trigger

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl command
        run: |
          curl -i -X POST https://nodejs-production-0625.up.railway.app/webhook/Content \
            -H "Content-Type: application/json" \
            -d '{"user_query":"feel-good Hindi series under 30 mins","region":"IN"}'
